services:
  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik_proxy
    dns:
      - 8.8.8.8
      - 8.8.4.4
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.backoffice.rule=Host(`admin.metacheetah.ir`)"
      - "traefik.http.routers.backoffice.entrypoints=websecure"
      - "traefik.http.routers.backoffice.tls=true"
      - "traefik.http.routers.backoffice.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backoffice.service=backoffice-svc"
      - "traefik.http.services.backoffice-svc.loadbalancer.server.port=80"
      - "traefik.http.routers.backoffice.middlewares=compress@file"
    restart: unless-stopped
networks:
  traefik_proxy:
    external: true