import { ApiService, ApiServiceDetail } from "./types";

export const mockCategories = [
  { id: "1", name: "پردازش تصویر", slug: "image-processing" },
  { id: "2", name: "پردازش ویدیو", slug: "video-processing" },
  { id: "3", name: "پردازش متن", slug: "text-processing" },
  { id: "4", name: "هوش مصنوعی", slug: "ai" },
  { id: "5", name: "تبدیل فرمت", slug: "format-conversion" },
];

export const mockApiServices: ApiService[] = [
  {
    id: "1",
    name: "تبدیل تصویر به متن",
    description: "تبدیل تصاویر به متن با استفاده از OCR",
    endpoint: "https://api.example.com/ocr",
    category_id: "1",
    category_name: "پردازش تصویر",
    slug: "image-to-text",
    english_name: "Image to Text OCR",
    is_active: true,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T15:30:00Z",
    metadata: {
      price: 1000,
      icon: "image",
    },
  },
  {
    id: "2",
    name: "تبدیل ویدیو به صدا",
    description: "استخراج صدای ویدیو و تبدیل به فرمت صوتی",
    endpoint: "https://api.example.com/video-to-audio",
    category_id: "2",
    category_name: "پردازش ویدیو",
    slug: "video-to-audio",
    english_name: "Video to Audio",
    is_active: true,
    createdAt: "2024-01-16T11:00:00Z",
    updatedAt: "2024-01-18T14:20:00Z",
    metadata: {
      price: 2000,
      icon: "video",
    },
  },
  {
    id: "3",
    name: "خلاصه‌سازی متن",
    description: "خلاصه‌سازی متن با استفاده از هوش مصنوعی",
    endpoint: "https://api.example.com/summarize",
    category_id: "3",
    category_name: "پردازش متن",
    slug: "text-summarization",
    english_name: "Text Summarization",
    is_active: true,
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-01-19T10:15:00Z",
    metadata: {
      price: 500,
      icon: "text",
    },
  },
  {
    id: "4",
    name: "تشخیص چهره",
    description: "تشخیص و شناسایی چهره در تصاویر",
    endpoint: "https://api.example.com/face-detection",
    category_id: "4",
    category_name: "هوش مصنوعی",
    slug: "face-detection",
    english_name: "Face Detection",
    is_active: true,
    createdAt: "2024-01-18T12:00:00Z",
    updatedAt: "2024-01-20T09:45:00Z",
    metadata: {
      price: 1500,
      icon: "face",
    },
  },
  {
    id: "5",
    name: "تبدیل فرمت ویدیو",
    description: "تبدیل فرمت ویدیو به فرمت‌های مختلف",
    endpoint: "https://api.example.com/video-convert",
    category_id: "5",
    category_name: "تبدیل فرمت",
    slug: "video-convert",
    english_name: "Video Format Converter",
    is_active: true,
    createdAt: "2024-01-19T08:00:00Z",
    updatedAt: "2024-01-21T11:30:00Z",
    metadata: {
      price: 3000,
      icon: "convert",
    },
  },
  {
    id: "6",
    name: "ترجمه متن",
    description: "ترجمه متن به زبان‌های مختلف",
    endpoint: "https://api.example.com/translate",
    category_id: "3",
    category_name: "پردازش متن",
    slug: "text-translation",
    english_name: "Text Translation",
    is_active: false,
    createdAt: "2024-01-20T13:00:00Z",
    updatedAt: "2024-01-22T14:20:00Z",
    metadata: {
      price: 800,
      icon: "translate",
    },
  },
  {
    id: "7",
    name: "تولید تصویر از متن",
    description: "تولید تصویر از متن با استفاده از AI",
    endpoint: "https://api.example.com/text-to-image",
    category_id: "4",
    category_name: "هوش مصنوعی",
    slug: "text-to-image",
    english_name: "Text to Image",
    is_active: true,
    createdAt: "2024-01-21T10:30:00Z",
    updatedAt: "2024-01-23T09:45:00Z",
    metadata: {
      price: 2500,
      icon: "ai-image",
    },
  },
  {
    id: "8",
    name: "فشرده‌سازی تصویر",
    description: "فشرده‌سازی تصویر با حفظ کیفیت",
    endpoint: "https://api.example.com/image-compress",
    category_id: "1",
    category_name: "پردازش تصویر",
    slug: "image-compression",
    english_name: "Image Compression",
    is_active: true,
    createdAt: "2024-01-22T14:00:00Z",
    updatedAt: "2024-01-24T10:15:00Z",
    metadata: {
      price: 300,
      icon: "compress",
    },
  },
];

export const mockApiServiceDetails: Record<string, ApiServiceDetail> = {
  "1": {
    ...mockApiServices[0],
    parameters: [
      {
        id: "1",
        name: "تصویر",
        type: "IMAGE",
        required: true,
        priority: 1,
      },
      {
        id: "2",
        name: "زبان خروجی",
        type: "SELECT",
        required: false,
        priority: 2,
        default_value: "fa",
        options: ["fa", "en", "ar"],
      },
    ],
    credit_costs: [
      {
        id: "1",
        user_id: null,
        credit_cost: 10,
      },
    ],
  },
  "2": {
    ...mockApiServices[1],
    parameters: [
      {
        id: "3",
        name: "فایل ویدیو",
        type: "VIDEO",
        required: true,
        priority: 1,
      },
      {
        id: "4",
        name: "فرمت خروجی",
        type: "SELECT",
        required: false,
        priority: 2,
        default_value: "mp3",
        options: ["mp3", "wav", "ogg"],
      },
    ],
    credit_costs: [
      {
        id: "2",
        user_id: null,
        credit_cost: 20,
      },
    ],
  },
  "3": {
    ...mockApiServices[2],
    parameters: [
      {
        id: "5",
        name: "متن",
        type: "TEXT",
        required: true,
        priority: 1,
      },
      {
        id: "6",
        name: "طول خلاصه",
        type: "NUMBER",
        required: false,
        priority: 2,
        default_value: "100",
      },
    ],
    credit_costs: [
      {
        id: "3",
        user_id: null,
        credit_cost: 5,
      },
    ],
  },
};
