import { ServiceRequest } from "./types";

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: "1",
    user_id: "user_1",
    user_phone: "09123456789",
    user_name: "علی محمدی",
    api_service_id: "1",
    api_service_name: "تبدیل تصویر به متن",
    input_params: {
      image: "image_123.jpg",
      language: "fa",
    },
    output: {
      text: "این یک متن نمونه است که از تصویر استخراج شده است.",
      confidence: 0.95,
    },
    error: null,
    status: "SUCCESS",
    credit_cost: 10,
    rating: 5,
    error_message: null,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:05Z",
  },
  {
    id: "2",
    user_id: "user_2",
    user_phone: "09123456790",
    user_name: "فاطمه احمدی",
    api_service_id: "2",
    api_service_name: "تبدیل ویدیو به صدا",
    input_params: {
      video: "video_456.mp4",
      format: "mp3",
    },
    output: null,
    error: "Error processing video",
    status: "FAILED",
    credit_cost: 20,
    rating: null,
    error_message: "فرمت ویدیو پشتیبانی نمی‌شود",
    createdAt: "2024-01-16T11:00:00Z",
    updatedAt: "2024-01-16T11:00:10Z",
  },
  {
    id: "3",
    user_id: "user_3",
    user_phone: "09123456791",
    user_name: "حسین رضایی",
    api_service_id: "3",
    api_service_name: "خلاصه‌سازی متن",
    input_params: {
      text: "این یک متن طولانی است که باید خلاصه شود...",
      length: 100,
    },
    output: {
      summary: "خلاصه متن...",
    },
    error: null,
    status: "PROCESSING",
    credit_cost: 5,
    rating: null,
    error_message: null,
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-01-17T09:00:02Z",
  },
  {
    id: "4",
    user_id: "user_1",
    user_phone: "09123456789",
    user_name: "علی محمدی",
    api_service_id: "4",
    api_service_name: "تشخیص چهره",
    input_params: {
      image: "face_789.jpg",
    },
    output: null,
    error: null,
    status: "PENDING",
    credit_cost: 15,
    rating: null,
    error_message: null,
    createdAt: "2024-01-18T12:00:00Z",
  },
  {
    id: "5",
    user_id: "user_4",
    user_phone: "09123456792",
    user_name: "زهرا کریمی",
    api_service_id: "1",
    api_service_name: "تبدیل تصویر به متن",
    input_params: {
      image: "image_321.jpg",
      language: "en",
    },
    output: {
      text: "This is sample text extracted from image.",
      confidence: 0.92,
    },
    error: null,
    status: "SUCCESS",
    credit_cost: 10,
    rating: 4,
    error_message: null,
    createdAt: "2024-01-19T08:00:00Z",
    updatedAt: "2024-01-19T08:00:04Z",
  },
  {
    id: "6",
    user_id: "user_5",
    user_phone: "09123456793",
    user_name: "محمد حسینی",
    api_service_id: "5",
    api_service_name: "تبدیل فرمت ویدیو",
    input_params: {
      video: "video_654.mp4",
      target_format: "avi",
    },
    output: {
      converted_file: "video_654.avi",
      size: "50MB",
    },
    error: null,
    status: "SUCCESS",
    credit_cost: 30,
    rating: 5,
    error_message: null,
    createdAt: "2024-01-20T13:00:00Z",
    updatedAt: "2024-01-20T13:05:00Z",
  },
  {
    id: "7",
    user_id: "user_2",
    user_phone: "09123456790",
    user_name: "فاطمه احمدی",
    api_service_id: "3",
    api_service_name: "خلاصه‌سازی متن",
    input_params: {
      text: "متن دیگری برای خلاصه‌سازی...",
    },
    output: null,
    error: "Timeout error",
    status: "FAILED",
    credit_cost: 5,
    rating: null,
    error_message: "زمان پردازش به پایان رسید",
    createdAt: "2024-01-21T10:30:00Z",
    updatedAt: "2024-01-21T10:35:00Z",
  },
  {
    id: "8",
    user_id: "user_6",
    user_phone: "09123456794",
    user_name: "مریم احمدی",
    api_service_id: "7",
    api_service_name: "تولید تصویر از متن",
    input_params: {
      text: "یک منظره زیبا از کوهستان",
      style: "realistic",
    },
    output: {
      image_url: "https://example.com/generated_image.jpg",
    },
    error: null,
    status: "SUCCESS",
    credit_cost: 25,
    rating: 5,
    error_message: null,
    createdAt: "2024-01-22T14:00:00Z",
    updatedAt: "2024-01-22T14:10:00Z",
  },
];
