import { ServiceRequest } from "./types";

export const mockServiceRequests: ServiceRequest[] = [
  {
    uuid: "1",
    userUuid: "user_1",
    apiServiceUuid: "service_1",
    taskId: "task_1",
    createdAt: "2024-01-15T10:00:00Z",
    parameters: {
      image: "image_123.jpg",
      language: "fa",
    },
    responseData: {
      text: "این یک متن نمونه است که از تصویر استخراج شده است.",
      confidence: 0.95,
    },
    status: "SUCCESS",
    creditCost: 10,
    paidWithGems: false,
    gemsUsed: 0,
    user: {
      uuid: "user_1",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      registrationSource: "web",
      referralCode: "REF001",
      phoneNumber: "09123456789",
      profile: {
        name: "علی محمدی",
      },
    },
    apiService: {
      uuid: "service_1",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      name: "تبدیل تصویر به متن",
      description: "تبدیل تصویر به متن با استفاده از OCR",
      endpoint: "/api/ocr",
      slug: "image-to-text",
      templateName: "ocr-template",
      serviceCreditCosts: [],
      metadata: {},
    },
  },
  {
    uuid: "2",
    userUuid: "user_2",
    apiServiceUuid: "service_2",
    taskId: "task_2",
    createdAt: "2024-01-16T11:00:00Z",
    parameters: {
      video: "video_456.mp4",
      format: "mp3",
    },
    responseData: null,
    status: "FAILED",
    creditCost: 20,
    paidWithGems: false,
    gemsUsed: 0,
    user: {
      uuid: "user_2",
      createdAt: "2024-01-02T00:00:00Z",
      updatedAt: "2024-01-02T00:00:00Z",
      registrationSource: "mobile",
      referralCode: "REF002",
      phoneNumber: "09123456790",
      profile: {
        name: "فاطمه احمدی",
      },
    },
    apiService: {
      uuid: "service_2",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      name: "تبدیل ویدیو به صدا",
      description: "استخراج صدا از ویدیو",
      endpoint: "/api/video-to-audio",
      slug: "video-to-audio",
      templateName: "video-to-audio-template",
      serviceCreditCosts: [],
      metadata: {},
    },
  },
  {
    uuid: "3",
    userUuid: "user_3",
    apiServiceUuid: "service_3",
    taskId: "task_3",
    createdAt: "2024-01-17T09:00:00Z",
    parameters: {
      text: "این یک متن طولانی است که باید خلاصه شود...",
      length: 100,
    },
    responseData: {
      summary: "خلاصه متن...",
    },
    status: "PROCESSING",
    creditCost: 5,
    paidWithGems: true,
    gemsUsed: 5,
    user: {
      uuid: "user_3",
      createdAt: "2024-01-03T00:00:00Z",
      updatedAt: "2024-01-03T00:00:00Z",
      registrationSource: "web",
      referralCode: "REF003",
      phoneNumber: "09123456791",
      profile: {
        name: "حسین رضایی",
      },
    },
    apiService: {
      uuid: "service_3",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      name: "خلاصه‌سازی متن",
      description: "خلاصه‌سازی متن با استفاده از AI",
      endpoint: "/api/summarize",
      slug: "text-summarize",
      templateName: "summarize-template",
      serviceCreditCosts: [],
      metadata: {},
    },
  },
  {
    uuid: "4",
    userUuid: "user_1",
    apiServiceUuid: "service_4",
    taskId: "task_4",
    createdAt: "2024-01-18T12:00:00Z",
    parameters: {
      image: "face_789.jpg",
    },
    responseData: null,
    status: "PENDING",
    creditCost: 15,
    paidWithGems: false,
    gemsUsed: 0,
    user: {
      uuid: "user_1",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      registrationSource: "web",
      referralCode: "REF001",
      phoneNumber: "09123456789",
      profile: {
        name: "علی محمدی",
      },
    },
    apiService: {
      uuid: "service_4",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      name: "تشخیص چهره",
      description: "تشخیص و شناسایی چهره در تصویر",
      endpoint: "/api/face-detection",
      slug: "face-detection",
      templateName: "face-detection-template",
      serviceCreditCosts: [],
      metadata: {},
    },
  },
  {
    uuid: "5",
    userUuid: "user_4",
    apiServiceUuid: "service_1",
    taskId: "task_5",
    createdAt: "2024-01-19T08:00:00Z",
    parameters: {
      image: "image_321.jpg",
      language: "en",
    },
    responseData: {
      text: "This is sample text extracted from image.",
      confidence: 0.92,
    },
    status: "SUCCESS",
    creditCost: 10,
    paidWithGems: false,
    gemsUsed: 0,
    user: {
      uuid: "user_4",
      createdAt: "2024-01-04T00:00:00Z",
      updatedAt: "2024-01-04T00:00:00Z",
      registrationSource: "mobile",
      referralCode: "REF004",
      phoneNumber: "09123456792",
      profile: {
        name: "زهرا کریمی",
      },
    },
    apiService: {
      uuid: "service_1",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      name: "تبدیل تصویر به متن",
      description: "تبدیل تصویر به متن با استفاده از OCR",
      endpoint: "/api/ocr",
      slug: "image-to-text",
      templateName: "ocr-template",
      serviceCreditCosts: [],
      metadata: {},
    },
  },
  {
    uuid: "6",
    userUuid: "user_5",
    apiServiceUuid: "service_5",
    taskId: "task_6",
    createdAt: "2024-01-20T13:00:00Z",
    parameters: {
      video: "video_654.mp4",
      target_format: "avi",
    },
    responseData: {
      converted_file: "video_654.avi",
      size: "50MB",
    },
    status: "SUCCESS",
    creditCost: 30,
    paidWithGems: true,
    gemsUsed: 30,
    user: {
      uuid: "user_5",
      createdAt: "2024-01-05T00:00:00Z",
      updatedAt: "2024-01-05T00:00:00Z",
      registrationSource: "web",
      referralCode: "REF005",
      phoneNumber: "09123456793",
      profile: {
        name: "محمد حسینی",
      },
    },
    apiService: {
      uuid: "service_5",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      name: "تبدیل فرمت ویدیو",
      description: "تبدیل فرمت ویدیو به فرمت‌های مختلف",
      endpoint: "/api/video-convert",
      slug: "video-convert",
      templateName: "video-convert-template",
      serviceCreditCosts: [],
      metadata: {},
    },
  },
  {
    uuid: "7",
    userUuid: "user_2",
    apiServiceUuid: "service_3",
    taskId: "task_7",
    createdAt: "2024-01-21T10:30:00Z",
    parameters: {
      text: "متن دیگری برای خلاصه‌سازی...",
    },
    responseData: null,
    status: "FAILED",
    creditCost: 5,
    paidWithGems: false,
    gemsUsed: 0,
    user: {
      uuid: "user_2",
      createdAt: "2024-01-02T00:00:00Z",
      updatedAt: "2024-01-02T00:00:00Z",
      registrationSource: "mobile",
      referralCode: "REF002",
      phoneNumber: "09123456790",
      profile: {
        name: "فاطمه احمدی",
      },
    },
    apiService: {
      uuid: "service_3",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      name: "خلاصه‌سازی متن",
      description: "خلاصه‌سازی متن با استفاده از AI",
      endpoint: "/api/summarize",
      slug: "text-summarize",
      templateName: "summarize-template",
      serviceCreditCosts: [],
      metadata: {},
    },
  },
  {
    uuid: "8",
    userUuid: "user_6",
    apiServiceUuid: "service_7",
    taskId: "task_8",
    createdAt: "2024-01-22T14:00:00Z",
    parameters: {
      text: "یک منظره زیبا از کوهستان",
      style: "realistic",
    },
    responseData: {
      image_url: "https://example.com/generated_image.jpg",
    },
    status: "SUCCESS",
    creditCost: 25,
    paidWithGems: false,
    gemsUsed: 0,
    user: {
      uuid: "user_6",
      createdAt: "2024-01-06T00:00:00Z",
      updatedAt: "2024-01-06T00:00:00Z",
      registrationSource: "web",
      referralCode: "REF006",
      phoneNumber: "09123456794",
      profile: {
        name: "مریم احمدی",
      },
    },
    apiService: {
      uuid: "service_7",
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
      name: "تولید تصویر از متن",
      description: "تولید تصویر از متن با استفاده از AI",
      endpoint: "/api/text-to-image",
      slug: "text-to-image",
      templateName: "text-to-image-template",
      serviceCreditCosts: [],
      metadata: {},
    },
  },
];
