import { UserCredit, UserCreditLog } from "./types";

export const mockUserCredits: UserCredit[] = [
  {
    id: "1",
    user_id: "user_1",
    user_name: "علی محمدی",
    user_phone: "09123456789",
    credit_amount: 500,
    source: "PURCHASE",
    expires_at: null,
    paid_amount: 50000,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T15:30:00Z",
  },
  {
    id: "2",
    user_id: "user_2",
    user_name: "فاطمه احمدی",
    user_phone: "09123456790",
    credit_amount: 1000,
    source: "GIFT",
    expires_at: null,
    paid_amount: 0,
    createdAt: "2024-01-16T11:00:00Z",
  },
  {
    id: "3",
    user_id: "user_3",
    user_name: "حسین رضایی",
    user_phone: "09123456791",
    credit_amount: 250,
    source: "REFERRAL",
    expires_at: "2024-12-31T23:59:59Z",
    paid_amount: 0,
    createdAt: "2024-01-17T09:00:00Z",
  },
  {
    id: "4",
    user_id: "user_1",
    user_name: "علی محمدی",
    user_phone: "09123456789",
    credit_amount: 300,
    source: "ADMIN",
    expires_at: null,
    paid_amount: 0,
    createdAt: "2024-01-18T12:00:00Z",
  },
];

export const mockUserCreditLogs: UserCreditLog[] = [
  {
    id: "1",
    user_id: "user_1",
    user_name: "علی محمدی",
    credit_amount: 500,
    type: "INCREASE",
    source: "PURCHASE",
    package_id: "pkg_1",
    service_id: null,
    is_confirmed: true,
    description: "خرید پکیج 500 اعتباری",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    user_id: "user_1",
    user_name: "علی محمدی",
    credit_amount: -10,
    type: "DECREASE",
    source: "PURCHASE",
    package_id: null,
    service_id: "1",
    is_confirmed: true,
    description: "استفاده از سرویس تبدیل تصویر به متن",
    createdAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "3",
    user_id: "user_2",
    user_name: "فاطمه احمدی",
    credit_amount: 1000,
    type: "INCREASE",
    source: "GIFT",
    package_id: null,
    service_id: null,
    is_confirmed: true,
    description: "اعتبار هدیه",
    createdAt: "2024-01-16T11:00:00Z",
  },
  {
    id: "4",
    user_id: "user_3",
    user_name: "حسین رضایی",
    credit_amount: 250,
    type: "INCREASE",
    source: "REFERRAL",
    package_id: null,
    service_id: null,
    is_confirmed: true,
    description: "پاداش معرفی کاربر",
    createdAt: "2024-01-17T09:00:00Z",
  },
  {
    id: "5",
    user_id: "user_1",
    user_name: "علی محمدی",
    credit_amount: -20,
    type: "DECREASE",
    source: "PURCHASE",
    package_id: null,
    service_id: "2",
    is_confirmed: true,
    description: "استفاده از سرویس تبدیل ویدیو به صدا",
    createdAt: "2024-01-18T10:00:00Z",
  },
  {
    id: "6",
    user_id: "user_1",
    user_name: "علی محمدی",
    credit_amount: 300,
    type: "INCREASE",
    source: "ADMIN",
    package_id: null,
    service_id: null,
    is_confirmed: true,
    description: "افزودن دستی توسط ادمین",
    createdAt: "2024-01-18T12:00:00Z",
  },
];
