import {
  CREDIT_LEDGER_STATUSES,
  CREDIT_LEDGER_TYPES,
  type CreditLedgerStatus,
  type CreditLedgerType,
} from "./types";

export const CREDIT_LEDGER_QUERY_KEY = "credit-ledger-history" as const;

export const CREDIT_LEDGER_PAGE_SIZES = [10, 25, 50] as const;

export const CREDIT_LEDGER_DEFAULT_LIMIT = 25;

export const CREDIT_LEDGER_TYPE_OPTIONS: CreditLedgerType[] = [
  CREDIT_LEDGER_TYPES.PURCHASE,
  CREDIT_LEDGER_TYPES.USAGE,
  CREDIT_LEDGER_TYPES.REFUND,
  CREDIT_LEDGER_TYPES.GIFT,
  CREDIT_LEDGER_TYPES.TRANSFER,
  CREDIT_LEDGER_TYPES.ADMIN,
  CREDIT_LEDGER_TYPES.EXPIRE,
  CREDIT_LEDGER_TYPES.INVENTORY,
];

export const CREDIT_LEDGER_STATUS_OPTIONS: CreditLedgerStatus[] = [
  CREDIT_LEDGER_STATUSES.PENDING,
  CREDIT_LEDGER_STATUSES.SUCCESS,
  CREDIT_LEDGER_STATUSES.FAILED,
  CREDIT_LEDGER_STATUSES.REVERSED,
];
